# Generated by Django 3.1.5 on 2021-02-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0015_apply_leave_admin_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_leave',
            name='admin_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
